// <auto-generated />
using System;
using CatalogService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251218131616_InitialCatalogSchema")]
    partial class InitialCatalogSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.API.Models.DefaultLayerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("defaultLayerGroups");
                });

            modelBuilder.Entity("CatalogService.API.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseSvgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsBaseConcept")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("CatalogService.API.Models.ModelPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LayerOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SvgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("isOptional")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelParts");
                });

            modelBuilder.Entity("CatalogService.API.Models.PartCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompatibleWithPartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourcePartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompatibleWithPartId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SourcePartId");

                    b.ToTable("partCompatibilities");
                });

            modelBuilder.Entity("CatalogService.API.Models.DefaultLayerGroup", b =>
                {
                    b.HasOne("CatalogService.API.Models.Model", null)
                        .WithMany("DefaultLayerGroups")
                        .HasForeignKey("ModelId");
                });

            modelBuilder.Entity("CatalogService.API.Models.ModelPart", b =>
                {
                    b.HasOne("CatalogService.API.Models.Model", "Model")
                        .WithMany("Parts")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CatalogService.API.Models.PartCompatibility", b =>
                {
                    b.HasOne("CatalogService.API.Models.ModelPart", "CompatibleWithPart")
                        .WithMany()
                        .HasForeignKey("CompatibleWithPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CatalogService.API.Models.Model", null)
                        .WithMany("PartCompatibilities")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CatalogService.API.Models.ModelPart", "SourcePart")
                        .WithMany()
                        .HasForeignKey("SourcePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompatibleWithPart");

                    b.Navigation("SourcePart");
                });

            modelBuilder.Entity("CatalogService.API.Models.Model", b =>
                {
                    b.Navigation("DefaultLayerGroups");

                    b.Navigation("PartCompatibilities");

                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
